#!/bin/bash
# GitHub 推送脚本
# 请在本地执行以下命令

echo "=========================================="
echo "AI Dev Hub - GitHub 推送指南"
echo "=========================================="
echo ""
echo "步骤 1: 克隆你的空仓库到本地"
echo "------------------------------------------"
echo "git clone https://github.com/FOURTEEN1416/AI-.git"
echo "cd AI-"
echo ""
echo "步骤 2: 复制项目文件到仓库目录"
echo "------------------------------------------"
echo "# 将 ai-dev-hub 目录下的所有文件复制到 AI- 目录"
echo "cp -r /path/to/ai-dev-hub/* ."
echo ""
echo "步骤 3: 添加并提交文件"
echo "------------------------------------------"
echo "git add ."
echo "git commit -m 'Initial commit: AI Developer Opportunity Hub'"
echo ""
echo "步骤 4: 推送到 GitHub"
echo "------------------------------------------"
echo "git push origin main"
echo ""
echo "=========================================="
echo "或者，如果你已经有仓库，直接添加远程地址:"
echo "------------------------------------------"
echo "cd /path/to/ai-dev-hub"
echo "git remote add origin https://github.com/FOURTEEN1416/AI-.git"
echo "git branch -M main"
echo "git push -u origin main"
echo "=========================================="
